### PR TITLE
minor typo ," --> ",

### PR DESCRIPTION
**Pull request by adrienbrunet**

### CODE REVIEW

**Comment by hjwp** [comment]
I'm afraid that's the completely-weird-and-illogical US style rules for punctuation and quotes.  https://www.grammar-monster.com/lessons/quotation_(speech)_marks_punctuation_in_or_out.htm

**Comment by hjwp** [comment]
OR insist on it :sob:

**Comment by adrienmindee** [comment]
I've spotted it elsewhere in the book and started to consider my whole life was a lie. I definitely lack knowledge on obscure style rules (uk vs us). Let's accept it... for now :imp:

**Comment by adrienbrunet** [comment]
I've spotted it elsewhere in the book and started to consider my whole life was a lie. I definitely lack knowledge on obscure style rules (uk vs us). Let's accept it... for now 👿

**Pull request closed without merging**
