### PR TITLE
Fix typo in info box

### PR DESCRIPTION
**Pull request by josteinl**

### CODE REVIEW

**Comment by hjwp** [comment]
thanks! but it wasn't a typo -- "worked example" means "an example that includes an explanation of how it is worked through" , ie an example showing the steps along the way.

**Comment by hjwp** [comment]
how are you enjoying the book in general?

**Comment by josteinl** [comment]
I am sorry for bothering you with nonsense. As you probably noticed, I am
not an English native speaker.

I finally got my paper copy of your book (over two months after ordering),
and am reading it again now. I like it a lot, and recommending it to all my
colleagues.

Best regards



Jostein Leira


man. 3. aug. 2020 kl. 12:31 skrev Harry Percival <notifications@github.com>:

**Comment by hjwp** [comment]
Jostein of course! now I remember. I have you in the acknowledgements 😊 

if you have a spare moment, the book could always do with another review on amazon, or wherever you like to put reviews...

**Pull request closed without merging**
