### PR TITLE
Add missing word.

### PR DESCRIPTION
**Pull request by markotibold**

### CODE REVIEW

**Comment by hjwp** [comment]
thanks!

how are you enjoying the book?

**Comment by markotibold** [comment]
So far it has been great! Thanks!


On 3 May 2020 at 14:40:50, Harry Percival (notifications@github.com) wrote:

thanks!

how are you enjoying the book?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cosmicpython/book/pull/303#issuecomment-623104074>, or
unsubscribe

**Comment by hjwp** [comment]
thanks :blush: 

when you feel ready, can i ask you to do a quick review on amazon (or wherever you like to put reviews)?  they really help in the early days.

and please do send any other PRs, suggestions, and feedback!

**Comment by markotibold** [comment]
HI Harry,

I would be happy to oblige on any of your suggestions when the time comes.

Cheers,

Marko


On 4 May 2020 at 11:08:34, Harry Percival (notifications@github.com) wrote:

thanks 😊

when you feel ready, can i ask you to do a quick review on amazon (or
wherever you like to put reviews)? they really help in the early days.

and please do send any other PRs, suggestions, and feedback!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cosmicpython/book/pull/303#issuecomment-623348246>, or
unsubscribe

**Pull request merged**
