### PR TITLE
Appendix validation - update args order in example

### PR DESCRIPTION
**Pull request by adrienbrunet**
line 372, we have `def product_exists(event, uow)`

### CODE REVIEW

**Comment by hjwp** [comment]
thanks again again.

the code in this chapter never got its own branch and set of tests you see, that's why it has the occasional bug...

**Comment by hjwp** [comment]
it's a good appendix tho right?  i hope people don't skip it...

**Comment by adrienbrunet** [comment]
haha it is ! I was grumbling about validation few days ago. Should this live in this new domain layer thing ? Directly in my route ? Where are you Harry ? Bob ? What are the rules ? But then I finished the book and found the last guidelines I needed. One of the most important sentence of this book about architectural matters is "it depends".

In the example you give, we first ensure some rules are respected but we're not sanitizing, or returning any modified data. Then, we apply logic. Which is perfect but I sometimes tend to be lazy and validate / modify my data at the same time. Anyway, I need to give it a few days.

Now that I've finished the book, @bobthemighty @hjwp, thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you ....

**Comment by hjwp** [comment]
:heart:

**Pull request merged**
