### PR TITLE
hynek notes in appendix validation

### PR DESCRIPTION
**Pull request by hjwp**

### CODE REVIEW

**Comment by hynek** [comment]
Some more weight to my rambling: https://tools.ietf.org/html/draft-thomson-postel-was-wrong-00

**Comment by bobthemighty** [comment]
Hey @hynek ! I think perhaps this debate is for another time, face to face, over the beverage of your choice.

I've read the RFC before, but I don't agree with its conclusions.  I think that the internet is a system of such extraordinary scale and resilience that it's difficult to suggest Postel's law has been *harmful* to its overall development.

It's true that the robustness principle hasn't helped with the general messiness of the world's largest software system, but it's absolutely helped it to evolve over time while continuing to function.

My sincerely held belief is that "continues to function while evolving" is vastly more important for most systems than "is formally correct at this specific moment in time".

This particular RFC is notably out of step with the philosophy of the IETF itself, which is best captured here, imho:

> In many ways, the IETF runs on the beliefs of its participants. One of the "founding beliefs" is embodied in an early quote about the IETF from David Clark: "We reject kings, presidents and voting. We believe in rough consensus and running code". Another early quote that has become a commonly-held belief in the IETF comes from Jon Postel: "Be conservative in what you send and liberal in what you accept".

**Comment by hynek** [comment]
Firstly: my mistake for not linking a more up to date version of the RFC draft that has more examples including my favorite one: TLS and the pain it was to move past SSLv3/TLSv1 – I have updated my original comment.

> My sincerely held belief is that "continues to function while evolving" is vastly more important for most systems than "is formally correct at this specific moment in time".

The question is how it would have evolved, if we hadn’t spend billions on supporting ancient F5 firewall stacks or making the simplest sites work across all browsers.

> I think perhaps this debate is for another time, face to face, over the beverage of your choice.

Well it’s your book, all I can do is give you my humble opinion and experiences. It’s very much your prerogative to decide otherwise. `¯\_(ツ)_/¯`  But:I personally find the idea of passing an argument and a command/system just ignores it distressing (another example I forgot: misspelling an argument that makes a destructive action nondestructive and the system happily ignores it and does the destructive thing).

**Comment by bobthemighty** [comment]
Unpicking this slightly, I think there are two differences in our thinking that may help explain our disagreement.

>I personally find the idea of passing an argument and a command/system just ignores it distressing

Overwhelmingly, I don't pass commands to systems. That's just not a thing that I do. The systems I architect are usually invoked by _events_ raised by other services. I hope it's uncontroversial that I should ignore additional fields in events because I'm not the only intended recipient. With events, *I'm* the one who's the client, and I have to conform to what is available, whereas with commands, I'm the server, and I can impose what restrictions I like.

If the procurement system and the analytics system need to make a non-breaking change to the schema of an event, they should be able to do so without also updating every other system that consumes the event, because that cripples our ability to evolve.

 > (another example I forgot: misspelling an argument that makes a destructive action nondestructive and the system happily ignores it and does the destructive thing).

In a system where I've carefully separated out my use-cases and distinguished between queries and commands, what does this _mean_? 

The case "DeleteAllMyStuff(not_realy=True)" doesn't work, because the command can't return any data to me, so I'll have no idea what it might have achieved.

The case "DeleteAllMyStuff(actually_just_mark_it=True)" doesn't work either, because I should separate "Delete Stuff" from "Mark Stuff" as distinct use-cases with their own logic.

**Comment by hjwp** [comment]
> The systems I architect are usually invoked by events raised by other services

i feel like thiis is the crux of it.  if you're using events as an integration platform, you'd make your life very difficult if you had to change every downstream system every time an upstream one added an optional field.   and the systems you receive events from are inside your own organisation, so you have some degree of control + trust for them.

if you're presenting a public API on the big bad internets, i can see how being much less permissive about what counts as valid input makes more sense.   you have basically no control over what people are going to send, so rejecting anything remotely weird might be reassuring.

**Comment by xtaje** [comment]
If you dig into the [history](https://ironick.typepad.com/ironick/2005/05/my_history_of_t.html) (technology hermeneutics!), I think there are some interesting nuances. (technology hermeneutics)

Postel's Law was originally intended to cover multiple implementations that may take different interpretations of the _same_ "immutable" standard.  It wasn't originally supposed to be about allowing interoperation of evolving standards.

It wasn't until RFC 1122 (9 years after the principle was first mentioned), that "adaptability" became a concern, which _could_ be interpreted as "extensibility".  And this was not written by Postel.  1122 also says that "software should be written to deal with every conceivable error..."

I think the `DeleteAllMyStuff` example demonstrates this last point.  And the strawman with a mispelled argument would not be respecting RFC1122. When you design your API, you need to be smart about what you accept liberally, and what you reject.

Another important thing is that designing an open standard like TCP, there are effectively an unbounded number of combinations of sender + receiver implementations. But in an API like this, the host effectively provides the reference implementation, and the number of client implementations is reasonably limited.   In the former case, the "Harmful Consequences" points make a lot of sense, but for the latter, Postel provides a reasonable heuristic.

**Comment by hjwp** [comment]
i had a bash at calling out the "postel was wrong" reaction here, let me know if y'all like it? https://github.com/cosmicpython/book/pull/221

**Comment by hynek** [comment]
> i had a bash at calling out the "postel was wrong" reaction here, let me know if y'all like it? #221

I have no interest in arguing about this point as I've mentioned above, so calling out the fact there's different takes on this is above and beyond for me.

**Comment by hjwp** [comment]
:ok_hand: :heart:

**Pull request merged**
