### PR TITLE
Fix wrong function name

### PR DESCRIPTION
**Pull request by mvtenorio**
The function name is "sync", not "synchronise_dirs"

### CODE REVIEW

**Comment by hjwp** [comment]
good catch thanks! 

how are you enjoying the book so far?

**Comment by mvtenorio** [comment]
It's been very helpful as I have to deal with similar problems at work. Thanks for making it available here!

**Comment by hjwp** [comment]
awesome!   we have a small community on the DDD-CQRS/ES slack here, come and join us in #python -- https://j.mp/ddd-es-cqrs  -- we always want to hear from more people doing this stuff, with python, in prod.

and if you have a moment, the book could always do with more reviews on amazon, or wherever you like to put reviews!

**Comment by mvtenorio** [comment]
great! I'll check it out

**Pull request merged**
