### PR TITLE
Fix wording

### PR DESCRIPTION
**Pull request by jugmac00**

### CODE REVIEW

**Comment by hjwp** [comment]
you know I think bob actually intended it that way? the `as` is optional.  but it's a less-used turn of phrase, even if it is probably grammatically correct.  I think changing it to the more common form is an improvement.  thanks Jürgen!

**Comment by jugmac00** [comment]
Well, I took a high risk, and I'd be equally happy if it's no wording issue and I learn something new.

This reminds me of an email I sent to Martin Fowler pointing out that he wrote `iff` instead of `if` in one of his blog posts - obviously, only after I got reassurance from my colleague from England.

**Comment by hjwp** [comment]
haha, i guess unfortunately you didn't ask a sufficiently nerdy colleague from England?

**Comment by hjwp** [comment]
anyways, what i'm trying to say here is, please keep the suggestions coming!

**Comment by jugmac00** [comment]
> haha, i guess unfortunately you didn't ask a sufficiently nerdy colleague from England?

We only have one for the quota.

**Comment by xtaje** [comment]
> you know I think bob actually intended it that way? the `as` is optional. but it's a less-used turn of phrase, even if it is probably grammatically correct. I think changing it to the more common form is an improvement. thanks Jürgen!

To be fair, I think it's more common in UK than US English,  and something that would take a German to flag 😛 .

**Pull request merged**
