### PR TITLE
Just to be consistent with previous cases

### PR DESCRIPTION
**Pull request by zhangcheng**

### CODE REVIEW

**Review by hjwp — APPROVED** [review]

**Comment by hjwp** [comment]
briliiant thank you!  how are you enjoying the book?

**Comment by zhangcheng** [comment]
> briliiant thank you! how are you enjoying the book?

Really enjoy the book's flow, and the thought process behind it.
I didn't notice there is a published book in simplified Chinese translation available, nor a volunteer translation of digital text out there.
If there is a simplified Chinese translation copy available, more people in mainland China could learn from your invaluable and eye-opening works.

**Comment by hjwp** [comment]
apparently there is a simplified Chinese translation in the works, from a company called `China Electric Power Press` ?

**Comment by zhangcheng** [comment]
Good to hear that. @hjwp

**Pull request merged**
