### PR TITLE
Poor Man -> Pure DI

### PR DESCRIPTION
**Pull request by xtaje**
Mark Seeman prefers this terminology now for reasons of [inclusivity](https://blog.ploeh.dk/2014/06/10/pure-di/).

### CODE REVIEW

**Comment by hjwp** [comment]
hm, i don't read that as reasons of inclusivity.  more like PR reasons.  he doesn't want people to think manual DI is inferior to framework DI.  i don't read that as him being worried that poor people will be offended by the term, do you?

i'm just quite attached to the "poor man's" terminology now lol.

**Comment by xtaje** [comment]
> hm, i don't read that as reasons of inclusivity. more like PR reasons. he doesn't want people to think manual DI is inferior to framework DI. i don't read that as him being worried that poor people will be offended by the term, do you?
> 
> i'm just quite attached to the "poor man's" terminology now lol.

I must have mis-read his comment about being "slightly derogotoray".

**Comment by hjwp** [comment]
right.  in the meantime @hynek still wants me to change it because it's not gender-neutral enough, sigh.  I'm thinking "manual DI" maybe.

**Comment by hynek** [comment]
Manual DI is superior for the reason alone that it _means_ something. :) “Poor man’s X” is just a way to derogate something which is fine in speech but poor form in a book IMHO.

**Comment by xtaje** [comment]
There was a kerfuffle last year where someone was upset by the term "DDD", with the reason that it was sexist due to an association with the sizing of women's anatomy.

I suppose the OR editors will have a definitive call on this, but given how diverse the Python community is and how much it emphasizes inclusivity, it would be prudent to change, especially since there's already a preferred term-of-art.

**Comment by hjwp** [comment]
yep, y'all have convinced me. am on it.

**Pull request closed without merging**
